image: docker

services:
  - docker:dind

stages:
  - build

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

build:
  stage: build
  only:
    - develop
    - main
    - master
  script:
    - docker build -t ${IMAGE} .
    - docker push ${IMAGE}
